### ISSUE TITLE
Build is breaking in consuming app

### ISSUE THREAD

**Issue by sandersky** [ciena-frost/ember-frost-core#431]
When consuming the version published from https://github.com/ciena-frost/ember-frost-core/pull/429 I get the following error:
```
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[1]
TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[1]
    at BroccoliMergeTrees.Plugin (/Repositories/UI/frost-orchestrate-ui/node_modules/broccoli-plugin/index.js:23:13)
    at new BroccoliMergeTrees (/Repositories/UI/frost-orchestrate-ui/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Repositories/UI/frost-orchestrate-ui/node_modules/broccoli-merge-trees/index.js:36:53)
    at CoreObject.treeForPublic (/Repositories/UI/frost-orchestrate-ui/node_modules/ember-frost-core/index.js:226:12)
    …
```

**Comment by sglanzer-fire** [comment]
We'll be on this first thing today

**Comment by sandersky** [comment]
@srowhani already fixed it
