### ISSUE TITLE
Error when installed into an app running v2.14.1 of Ember

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-core#474]
**STEPS TO REPLICATE**

1) Install `ember-cli@2.14.1`
2) Run `ember new testApp`
3) Run `ember install ember-frost-core`
4) Run `ember s` and receive this error:

```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
TypeError: The plugin [null,{}] didn't export a Plugin instance
    at PluginManager.validate (my-project/node_modules/ember-frost-core/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (my-project/node_modules/ember-frost-core/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (my-project/node_modules/ember-frost-core/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (my-project/node_modules/ember-frost-core/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (my-project/node_modules/ember-frost-core/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at my-project/node_modules/ember-frost-core/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:102:26
    at initializePromise (my-project/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (my-project/node_modules/rsvp/dist/rsvp.js:1033:31)
    at Object.transformString (my-project/node_modules/ember-frost-core/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:101:12)
    at Babel.transform (my-project/node_modules/ember-frost-core/node_modules/broccoli-babel-transpiler/index.js:110:22)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (my-project/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (my-project/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (my-project/node_modules/broccoli-merge-trees/index.js:36:53)
    at Class.treeForAddon (my-project/node_modules/ember-frost-core/index.js:190:12)
    at Class.superWrapper [as treeForAddon] (my-project/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (my-project/node_modules/ember-cli/lib/models/addon.js:551:33)
    at Class.treeFor (my-project/node_modules/ember-cli/lib/models/addon.js:511:21)
    at project.addons.map.addon (my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:557:22)
    at Array.map (native)
    at EmberApp.addonTreesFor (my-project/node_modules/ember-cli/lib/broccoli/ember-app.js:555:32)
```

**Comment by notmessenger** [comment]
This seems like a possible lead, especially with the fix that was implemented - https://github.com/ember-cli/ember-cli-mocha/issues/182

Specifically that it may not be an "obvious" reason.

**Comment by notmessenger** [comment]
The problem is due to a mismatch in the versions of `ember-cli-babel`.  If the application's version of `ember-cli-babel` is changed from `^6.3.0` to `^5.1.7` and the version of `ember-cli-htmlbars-inline-precompile` is changed from `^0.4.3` to `^0.3.0` then the application will build/serve without encountering this error.

**Comment by Blackening999** [comment]
Just killed 3hrs to find out why Ember project halts with "redux" not installed.

**Comment by Blackening999** [comment]
```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Cannot find module 'redux' from '/Users/machine-user/Work/My_Projects/some-project/tmp/plugin-output_path-cbzrUuiG.tmp'
    at /Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:49:14
    at process (/Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:177:43)
    at ondir (/Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:192:17)
    at load (/Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:73:43)
    at onex (/Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:96:31)
    at /Users/machine-user/Work/My_Projects/some-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:111:15)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Users/machine-user/Work/My_Projects/some-project/node_modules/broccoli-plugin/index.js:8:31)
    at new BroccoliMergeTrees (/Users/machine-user/Work/My_Projects/some-project/node_modules/broccoli-merge-trees/index.js:42:10)
    at Class.postprocessTree (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-browserify/lib/index.js:66:14)
    at projectOrAddon.addons.reduce (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:7:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at Class._addonPostprocessTree (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/models/addon.js:413:12)
    at Class.processedAddonJsFiles (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/models/addon.js:1172:37)
    at Class.compileAddon (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/models/addon.js:1080:24)
    at Class.treeForAddon (/Users/machine-user/Work/My_Projects/some-project/node_modules/ember-cli/lib/models/addon.js:738:26)
```

**Comment by Blackening999** [comment]
Your fix isn't helping
BLOCKER....

**Comment by dguayrobotiq** [comment]
Is this fixed? I'm trying to update `ember-cli` to `2.18.0` and since `ember-frost-core` needs these old versions, I just can't upgrade without encountering multiple errors.

**Comment by notmessenger** [comment]
@dguayrobotiq This has not yet been fixed.  https://github.com/ciena-blueplanet/ember-prop-types/issues/158#issuecomment-370573212 provides more insight into the reason it has not been and when we are planning to do so.

**Comment by dguayrobotiq** [comment]
@notmessenger If I understand it correctly, If I want to upgrade to `ember-cli 2.13+`, all of my dependencies need to use `ember-cli 2.13+`?

**Comment by notmessenger** [comment]
According to https://emberjs.com/blog/2017/04/29/ember-2-13-released.html

>Babel 6 support has been added to Ember CLI internally and is now used by default for newly generated projects (both applications and addons). Due to the way that Ember CLI handles transpilation this transition can be done gradually by updating each addon to utilize newer versions of ember-cli-babel.

Which reads to me as if the transition from Babel 5 to Babel 6 should have never caused an issue (other than needing to change the version of `ember-cli-babel` being used) yet this change is specifically causing us issues and we have not been able to work in a mixed Babel environment.

We have not been able to determine whether others are experiencing similar issues (with apps and other addons (not ours)) or if enough projects moved forward around the time this switch over occurred that it didn't really manifest itself.   We have not seen any conversation in the community about the difficulties we have been experiencing so it is possible that this is a problem of our own making but we have not been able to determine what the issue is which would then allow us to do so piecemeal rather than having to do all at once (we have around 75 addons and dozens of apps).  To say that this is impacting us, and by extension others such as yourself, is an understatement.  We began having meetings this past week to figure out our game plan and we are going to dedicate some time to specifically digging into this problem and re-creating it as a smaller scale so we can involve the community at large in discovering a solution (besides just upgrading everything which is our ultimate desired end goal).
